name: Release Checker

on:
  schedule:
    - cron: '0 0 * * *' # midnights

jobs:
  Release-Checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Fetch latest release version
        id: fetch-release
        run: |
          curl -s https://api.github.com/repos/rclone/rclone/releases/latest | jq -r ".tag_name" > release-versions/latest.txt
          echo "success=$(test \"$(cat release-versions/latest.txt)\" != 'null' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Check for modified files
        id: git-check
        run: echo "modified=$([ -z "$(git status --porcelain)" ] && echo 'false' || echo 'true')" >> $GITHUB_OUTPUT

      - name: Commit & push latest release version
        if: |
          steps.fetch-release.outputs.success == 'true' &&
          steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Release: $(cat release-versions/latest.txt)"
          git push
